//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rcbi.Business.FluentValidator {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FluentValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidationResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rcbi.Business.FluentValidator.FluentValidationResource", typeof(FluentValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不是有效的信用卡号。 的本地化字符串。
        /// </summary>
        public static string CreditCardError {
            get {
                return ResourceManager.GetString("CreditCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除数据失败，ID：{id} 的本地化字符串。
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项为空 的本地化字符串。
        /// </summary>
        public static string DeleteItemIsEmpty {
            get {
                return ResourceManager.GetString("DeleteItemIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门编号已存在 的本地化字符串。
        /// </summary>
        public static string DeptCodeExists {
            get {
                return ResourceManager.GetString("DeptCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不是有效的电子邮件地址。 的本地化字符串。
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 应该和 &apos;{ComparisonValue}&apos; 相等。 的本地化字符串。
        /// </summary>
        public static string equal_error {
            get {
                return ResourceManager.GetString("equal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须是 {MaxLength} 字符长度，你已经输入了 {TotalLength} 字符。 的本地化字符串。
        /// </summary>
        public static string exact_length_error {
            get {
                return ResourceManager.GetString("exact_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须在 {From} 和 {To} (排除)之间， 你输入了 {Value}。 的本地化字符串。
        /// </summary>
        public static string exclusivebetween_error {
            get {
                return ResourceManager.GetString("exclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该设备编码已存在 的本地化字符串。
        /// </summary>
        public static string FaceRecoEquCodeExists {
            get {
                return ResourceManager.GetString("FaceRecoEquCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该字典项目已存在 的本地化字符串。
        /// </summary>
        public static string GeneralContentExists {
            get {
                return ResourceManager.GetString("GeneralContentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须大于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string greaterthan_error {
            get {
                return ResourceManager.GetString("greaterthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须大于或等于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string greaterthanorequal_error {
            get {
                return ResourceManager.GetString("greaterthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据为空 的本地化字符串。
        /// </summary>
        public static string ImportEmpty {
            get {
                return ResourceManager.GetString("ImportEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须在 {From} 和 {To} 之间， 你输入了 {Value}。 的本地化字符串。
        /// </summary>
        public static string inclusivebetween_error {
            get {
                return ResourceManager.GetString("inclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库插入失败 的本地化字符串。
        /// </summary>
        public static string InsertToDatabaseFail {
            get {
                return ResourceManager.GetString("InsertToDatabaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不是正确的IP地址。 的本地化字符串。
        /// </summary>
        public static string ipaddress_error {
            get {
                return ResourceManager.GetString("ipaddress_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 的长度必须在 {MinLength} 到 {MaxLength} 字符，您已经输入了 {TotalLength} 字符。 的本地化字符串。
        /// </summary>
        public static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须小于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string lessthan_error {
            get {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 必须小于或等于 &apos;{ComparisonValue}&apos;。 的本地化字符串。
        /// </summary>
        public static string lessthanorequal_error {
            get {
                return ResourceManager.GetString("lessthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单编码已存在 的本地化字符串。
        /// </summary>
        public static string MenuCodeExists {
            get {
                return ResourceManager.GetString("MenuCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级菜单不能选择为自己 的本地化字符串。
        /// </summary>
        public static string MenuParentIdEqualMenuId {
            get {
                return ResourceManager.GetString("MenuParentIdEqualMenuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已存在的项目设置 的本地化字符串。
        /// </summary>
        public static string MonitorConfigExists {
            get {
                return ResourceManager.GetString("MonitorConfigExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写 &apos;{PropertyName}&apos;。 的本地化字符串。
        /// </summary>
        public static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不能和 &apos;{PropertyValue}&apos; 相等。 的本地化字符串。
        /// </summary>
        public static string notequal_error {
            get {
                return ResourceManager.GetString("notequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库中不存在该条记录 的本地化字符串。
        /// </summary>
        public static string NotExistsRowRecord {
            get {
                return ResourceManager.GetString("NotExistsRowRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 不能为空。 的本地化字符串。
        /// </summary>
        public static string notnull_error {
            get {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织编码已存在 的本地化字符串。
        /// </summary>
        public static string OrgCodeExists {
            get {
                return ResourceManager.GetString("OrgCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数编码 的本地化字符串。
        /// </summary>
        public static string ParameterCode {
            get {
                return ResourceManager.GetString("ParameterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数名称 的本地化字符串。
        /// </summary>
        public static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该模具编号已存在 的本地化字符串。
        /// </summary>
        public static string PcMoldCodeExists {
            get {
                return ResourceManager.GetString("PcMoldCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该台座编号已存在 的本地化字符串。
        /// </summary>
        public static string PcPedestalCodeExists {
            get {
                return ResourceManager.GetString("PcPedestalCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前项目已包括该材料 的本地化字符串。
        /// </summary>
        public static string PcProcessMaterialExists {
            get {
                return ResourceManager.GetString("PcProcessMaterialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该仓库编号已存在 的本地化字符串。
        /// </summary>
        public static string PcWarehouseCodeExists {
            get {
                return ResourceManager.GetString("PcWarehouseCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该计划节点时间和其他节点时间存在重复 的本地化字符串。
        /// </summary>
        public static string PlanNodeDateInvalid {
            get {
                return ResourceManager.GetString("PlanNodeDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点下已存在明细计划，不可删除 的本地化字符串。
        /// </summary>
        public static string PlanNodeDeleteInvalid {
            get {
                return ResourceManager.GetString("PlanNodeDeleteInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该计划节点推进计划环数不能大于下个节点环数 的本地化字符串。
        /// </summary>
        public static string PlanNodeRingNumberInvalid {
            get {
                return ResourceManager.GetString("PlanNodeRingNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交参数错误 的本地化字符串。
        /// </summary>
        public static string PostParameterError {
            get {
                return ResourceManager.GetString("PostParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的条件不符合 &apos;{PropertyName}&apos;。 的本地化字符串。
        /// </summary>
        public static string predicate_error {
            get {
                return ResourceManager.GetString("predicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该项目编码已存在 的本地化字符串。
        /// </summary>
        public static string ProjectCodeExists {
            get {
                return ResourceManager.GetString("ProjectCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前项目已包括该构建单位 的本地化字符串。
        /// </summary>
        public static string ProjectOrgExists {
            get {
                return ResourceManager.GetString("ProjectOrgExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前项目已包括该构件类型 的本地化字符串。
        /// </summary>
        public static string ProjectPcTypeExists {
            get {
                return ResourceManager.GetString("ProjectPcTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该项目下的区间编码已经存在 的本地化字符串。
        /// </summary>
        public static string ProjectSectionCode {
            get {
                return ResourceManager.GetString("ProjectSectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该项目编号和和区间隧道编号已存在 的本地化字符串。
        /// </summary>
        public static string ProjectTunnelCode {
            get {
                return ResourceManager.GetString("ProjectTunnelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该项目编码或区间隧道编号或测点类型或监测编号已存在 的本地化字符串。
        /// </summary>
        public static string PrTuPoMo {
            get {
                return ResourceManager.GetString("PrTuPoMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 的格式不正确。 的本地化字符串。
        /// </summary>
        public static string regex_error {
            get {
                return ResourceManager.GetString("regex_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环号（环） 的本地化字符串。
        /// </summary>
        public static string RingNumber {
            get {
                return ResourceManager.GetString("RingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数类型 的本地化字符串。
        /// </summary>
        public static string RingParaType {
            get {
                return ResourceManager.GetString("RingParaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该角色编码已存在 的本地化字符串。
        /// </summary>
        public static string RoleCodeExists {
            get {
                return ResourceManager.GetString("RoleCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编码或名称不能为空 的本地化字符串。
        /// </summary>
        public static string RoleCodeOrNameRequired {
            get {
                return ResourceManager.GetString("RoleCodeOrNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; 总位数不能超过 {expectedPrecision} 位，其中整数部分 {expectedScale} 位。您填写了 {digits} 位小数和 {actualScale} 位整数。 的本地化字符串。
        /// </summary>
        public static string scale_precision_error {
            get {
                return ResourceManager.GetString("scale_precision_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统异常 的本地化字符串。
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该区间隧道编号或盾构机ID或编码已存在 的本地化字符串。
        /// </summary>
        public static string TuTbNa {
            get {
                return ResourceManager.GetString("TuTbNa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库更新失败 的本地化字符串。
        /// </summary>
        public static string UpdateToDatabaseFail {
            get {
                return ResourceManager.GetString("UpdateToDatabaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败 的本地化字符串。
        /// </summary>
        public static string UploadFail {
            get {
                return ResourceManager.GetString("UploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统检测为危险文件，重新上传请联系系统维护人员。 的本地化字符串。
        /// </summary>
        public static string UploadFileExtDanger {
            get {
                return ResourceManager.GetString("UploadFileExtDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户已存在 的本地化字符串。
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
    }
}
